### Python Libraries:
    

#### Numpy 

#### It was created in 2005 by Travis Oliphant
#### 

In [1]:
import numpy;
x=numpy.array([1,2,3,4])
print(x)

[1 2 3 4]


In [3]:
print(type(x))



<class 'numpy.ndarray'>


In [9]:
import numpy;
y=numpy.array([[1,2,3,4],[4,5,6,7]])
print(y)

[[1 2 3 4]
 [4 5 6 7]]


In [10]:
import numpy;
z=numpy.array([[1,2,3,4],[4,5,6,7],[9,10,11,12]])
print(z)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 9 10 11 12]]


In [11]:
print(z[2])


[ 9 10 11 12]


In [15]:
print(z[0,1])

2


In [16]:
print(z.ndim)

2


In [17]:
z.ndim

2

In [18]:
z.shape

(3, 4)

In [19]:
z.size

12

In [22]:
import numpy as np
s=np.array([1,2,3,4,5],ndmin=1)
print(s)

[1 2 3 4 5]


In [23]:
p=np.array([1,2,3,4,5],dtype=complex)
print(p)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]


In [30]:
import numpy as np
x=np.arange(10)
print (x)


[0 1 2 3 4 5 6 7 8 9]


In [34]:
x[::2]

array([0, 2, 4, 6, 8])

In [32]:
x[0:9:3]

array([0, 3, 6])

In [35]:
x[5::-2]

array([5, 3, 1])

In [36]:
x[5:1:-1]

array([5, 4, 3, 2])

In [37]:
a1=np.arange(100)
a1


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [40]:
a2=np.arange(100).reshape(10,10)
a2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [42]:
a4=np.arange(12).reshape(3,4)
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [43]:
s1=np.ones((3,3))
s1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [44]:
s2=s1+3
s2

array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

In [45]:
s3=np.zeros((4,4))
s3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [48]:
s4=np.threes((10,10))
s4

AttributeError: module 'numpy' has no attribute 'threes'

In [50]:
s5=s2-3
s5

array([[-5., -5., -5.],
       [-5., -5., -5.],
       [-5., -5., -5.]])

In [51]:
print(np.sin(a1))

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849 -0.54402111 -0.99999021
 -0.53657292  0.42016704  0.99060736  0.65028784 -0.28790332 -0.96139749
 -0.75098725  0.14987721  0.91294525  0.83665564 -0.00885131 -0.8462204
 -0.90557836 -0.13235175  0.76255845  0.95637593  0.27090579 -0.66363388
 -0.98803162 -0.40403765  0.55142668  0.99991186  0.52908269 -0.42818267
 -0.99177885 -0.64353813  0.29636858  0.96379539  0.74511316 -0.15862267
 -0.91652155 -0.83177474  0.01770193  0.85090352  0.90178835  0.12357312
 -0.76825466 -0.95375265 -0.26237485  0.67022918  0.98662759  0.39592515
 -0.55878905 -0.99975517 -0.521551    0.43616476  0.99287265  0.63673801
 -0.30481062 -0.96611777 -0.7391807   0.1673557   0.92002604  0.82682868
 -0.02655115 -0.85551998 -0.89792768 -0.11478481  0.77389068  0.95105465
  0.25382336 -0.67677196 -0.98514626 -0.38778164  0.56610764  0.99952016
  0.51397846 -0.44411267 -0.99388865 -0.62988799  0.

In [52]:
print(np.cos(a1))

[ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219
  0.96017029  0.75390225 -0.14550003 -0.91113026 -0.83907153  0.0044257
  0.84385396  0.90744678  0.13673722 -0.75968791 -0.95765948 -0.27516334
  0.66031671  0.98870462  0.40808206 -0.54772926 -0.99996083 -0.53283302
  0.42417901  0.99120281  0.64691932 -0.29213881 -0.96260587 -0.74805753
  0.15425145  0.91474236  0.83422336 -0.01327675 -0.84857027 -0.90369221
 -0.12796369  0.76541405  0.95507364  0.26664293 -0.66693806 -0.98733928
 -0.39998531  0.5551133   0.99984331  0.52532199 -0.43217794 -0.99233547
 -0.64014434  0.30059254  0.96496603  0.7421542  -0.16299078 -0.91828279
 -0.82930983  0.02212676  0.85322011  0.89986683  0.11918014 -0.77108022
 -0.95241298 -0.25810164  0.67350716  0.98589658  0.39185723 -0.56245385
 -0.99964746 -0.5177698   0.44014302  0.99339038  0.6333192  -0.30902273
 -0.96725059 -0.73619272  0.17171734  0.92175127  0.82433133 -0.03097503
 -0.85780309 -0.89597095 -0.11038724  0.77668598  0.

In [53]:
print(np.tan(a1))

[ 0.00000000e+00  1.55740772e+00 -2.18503986e+00 -1.42546543e-01
  1.15782128e+00 -3.38051501e+00 -2.91006191e-01  8.71447983e-01
 -6.79971146e+00 -4.52315659e-01  6.48360827e-01 -2.25950846e+02
 -6.35859929e-01  4.63021133e-01  7.24460662e+00 -8.55993401e-01
  3.00632242e-01  3.49391565e+00 -1.13731371e+00  1.51589471e-01
  2.23716094e+00 -1.52749853e+00  8.85165604e-03  1.58815308e+00
 -2.13489670e+00 -1.33526407e-01  1.17875355e+00 -3.27370380e+00
 -2.81429605e-01  8.87142844e-01 -6.40533120e+00 -4.41695568e-01
  6.61006041e-01 -7.53130148e+01 -6.23498963e-01  4.73814720e-01
  7.75047091e+00 -8.40771255e-01  3.10309661e-01  3.61455441e+00
 -1.11721493e+00  1.60656699e-01  2.29138799e+00 -1.49838734e+00
  1.77046993e-02  1.61977519e+00 -2.08661353e+00 -1.24527568e-01
  1.20012724e+00 -3.17290855e+00 -2.71900612e-01  9.03086149e-01
 -6.05327238e+00 -4.31158197e-01  6.73800101e-01 -4.51830879e+01
 -6.11273688e-01  4.84699227e-01  8.33085685e+00 -8.25774009e-01
  3.20040389e-01  3.74316

In [61]:
x=np.random.rand(2,5)
x

array([[0.31600536, 0.59078309, 0.10198054, 0.07866561, 0.13209026],
       [0.20344635, 0.07368659, 0.57861375, 0.36371385, 0.51059827]])

In [62]:
x1=np.random.randint(3,size=10)
x1

array([0, 0, 2, 2, 0, 1, 1, 0, 1, 1])

In [63]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_init', '_globals', '_mat', '_pytes

In [65]:
print(len(dir(np)))

620


In [67]:
np.__version__

'1.19.2'

### Filtering Arrays

In [68]:
import numpy as np
ary=np.array([11,12,13,14])
x=[True,False,True,False]
nary=ary[x]
print(nary)

[11 13]


In [69]:
import numpy as np
ary=np.array([11,12,13,14])
print(ary)
x=[True,False,True,False]
nary=ary[x]
print(nary)

[11 12 13 14]
[11 13]


In [70]:
ar=np.array([1,2,3,4,5])
filter_ar=ar%2==0
new_ar=ar[filter_ar]
print(filter_ar)
print(new_ar)

[False  True False  True False]
[2 4]


In [71]:
ar=np.array([1,2,3,4,5])
filter_ar=ar%2!=0
new_ar=ar[filter_ar]
print(filter_ar)
print(new_ar)

[ True False  True False  True]
[1 3 5]


In [72]:
ar=np.array([1,2,3,4,5])
filter_ar=ar%2==1
new_ar=ar[filter_ar]
print(filter_ar)
print(new_ar)

[ True False  True False  True]
[1 3 5]
