In [2]:
print("hello world")

hello world


### Day - 6 Agenda:
- Intro about Machine Learning
  - For Data Analysis 
    - Numpy
    - matplotlib
    - seaborn
  - types of machine Learning 
    - Supervised Learning
      - Classification
        - Support Vector Machines
        - Naive Bayes
        - K nearest neighbour
        - Random Forest
      - Regression
        - Linear Regression
        - Polynomial Regression
        - Logistic Regression
        - Decision Tree Regression
    - Unsupervised Learning
      - Clustering
        - K mean 
        - k median 
        - Som
        - Hirearchial
    - Reinforcement Learning
- Framework -Django
  - Develop basic application
- Heroku
   - Deploying our project into server
   - without Db
   - with Db(Protgres sql)

### T-shirt size prediction


In [3]:

import numpy as np
import pandas as pd


In [5]:
# Get the data from source file
data=pd.read_csv('tshirt.csv')
print(data)

    height  weight  size
0      158    58.0     M
1      158    59.0     M
2      180   120.0   XXL
3      158    63.0     M
4      160     NaN     M
5      120    45.0     S
6      170    80.0    XL
7      163    60.0     M
8      193   150.0   XXL
9      165    62.0     L
10     163    63.0     L
11     168    56.0     L
12     140    50.0     S
13     150    42.0     S
14     155    48.0     S
15     142     NaN     S
16     155    60.0     L
17     160   170.0  XXXL
18     182    90.0   XXL


In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   height  19 non-null     int64  
 1   weight  17 non-null     float64
 2   size    19 non-null     object 
dtypes: float64(1), int64(1), object(1)
memory usage: 584.0+ bytes


In [6]:
# data preprocessing
data.isnull().sum()

height    0
weight    2
size      0
dtype: int64

In [8]:
data.fillna(0)

height  weight  size
0      158    58.0     M
1      158    59.0     M
2      180   120.0   XXL
3      158    63.0     M
4      160     0.0     M
5      120    45.0     S
6      170    80.0    XL
7      163    60.0     M
8      193   150.0   XXL
9      165    62.0     L
10     163    63.0     L
11     168    56.0     L
12     140    50.0     S
13     150    42.0     S
14     155    48.0     S
15     142     0.0     S
16     155    60.0     L
17     160   170.0  XXXL
18     182    90.0   XXL

In [12]:
# huge No of Null Values
mean=data['weight'].mean()
print(mean)
data.fillna(mean)
data.bfill()

75.05882352941177


height  weight  size
0      158    58.0     M
1      158    59.0     M
2      180   120.0   XXL
3      158    63.0     M
4      160    45.0     M
5      120    45.0     S
6      170    80.0    XL
7      163    60.0     M
8      193   150.0   XXL
9      165    62.0     L
10     163    63.0     L
11     168    56.0     L
12     140    50.0     S
13     150    42.0     S
14     155    48.0     S
15     142    60.0     S
16     155    60.0     L
17     160   170.0  XXXL
18     182    90.0   XXL

In [13]:
# less Null Values in database
data=data.dropna()
print(data)

    height  weight  size
0      158    58.0     M
1      158    59.0     M
2      180   120.0   XXL
3      158    63.0     M
5      120    45.0     S
6      170    80.0    XL
7      163    60.0     M
8      193   150.0   XXL
9      165    62.0     L
10     163    63.0     L
11     168    56.0     L
12     140    50.0     S
13     150    42.0     S
14     155    48.0     S
16     155    60.0     L
17     160   170.0  XXXL
18     182    90.0   XXL


In [14]:
mean=data['weight'].mean()
print(mean)
data.fillna(mean)
data.bfill()

75.05882352941177


height  weight  size
0      158    58.0     M
1      158    59.0     M
2      180   120.0   XXL
3      158    63.0     M
5      120    45.0     S
6      170    80.0    XL
7      163    60.0     M
8      193   150.0   XXL
9      165    62.0     L
10     163    63.0     L
11     168    56.0     L
12     140    50.0     S
13     150    42.0     S
14     155    48.0     S
16     155    60.0     L
17     160   170.0  XXXL
18     182    90.0   XXL

In [21]:
# x=Input values(Features)//independent
# y=Output values(Target)//dependent
x=data[['weight','height']]
#print(x)
y=data['size']
#print(y)
from sklearn.preprocessing import LabelEncoder
y_label=LabelEncoder()
# convert char or string to int
Y=y_label.fit_transform(y)
#print(Y)

[1 1 4 1 2 3 1 4 0 0 0 2 2 2 0 5 4]


In [23]:
#Modeling
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
x_train,x_test,y_train,y_test=train_test_split(x,Y,test_size=0.3,random_state=3)
print(x_train,x_test,y_train,y_test)

    weight  height
12    50.0     140
2    120.0     180
14    48.0     155
6     80.0     170
0     58.0     158
13    42.0     150
17   170.0     160
3     63.0     158
10    63.0     163
9     62.0     165
11    56.0     168     weight  height
18    90.0     182
7     60.0     163
5     45.0     120
8    150.0     193
16    60.0     155
1     59.0     158 [2 4 2 3 1 2 5 1 0 0 0] [4 1 2 4 0 1]


In [24]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
x_train,x_test,y_train,y_test=train_test_split(x,Y,test_size=0.3,random_state=3)
print(x_train)

    weight  height
12    50.0     140
2    120.0     180
14    48.0     155
6     80.0     170
0     58.0     158
13    42.0     150
17   170.0     160
3     63.0     158
10    63.0     163
9     62.0     165
11    56.0     168


In [25]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
x_train,x_test,y_train,y_test=train_test_split(x,Y,test_size=0.3,random_state=3)
print(x_test)

    weight  height
18    90.0     182
7     60.0     163
5     45.0     120
8    150.0     193
16    60.0     155
1     59.0     158


In [26]:
#importing algorithm and apply to them
from sklearn.neighbors import KNeighborsClassifier

In [27]:
knn=KNeighborsClassifier(n_neighbors=5)
knn.fit(x_train,y_train)
print(knn.predict(x_test))

[0 0 2 0 0 0]


In [28]:
knn.predict([[48,155]])

array([2])

In [29]:
knn.predict([[120,180]])

array([0])

In [32]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,knn.predict(x_test))*100)

33.33333333333333
